In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/pradippokhrel45/optimizer-information/optuna1 (1).db
/kaggle/input/datasets/pradippokhrel45/coding-problem-of-alpaca-and-flytech-only/refined_train.jsonl
/kaggle/input/datasets/pradippokhrel45/llama-2-fine-tuning-datasets-for-python-code/train.jsonl

In [2]:
import shutil

shutil.copy(
    "/kaggle/input/datasets/pradippokhrel45/optimizer-information/optuna1 (1).db",
    "/kaggle/working/optuna1.db"
)

'/kaggle/working/optuna1.db'

In [3]:
!pip install trl bitsandbytes optuna accelerate

Collecting trl
  Downloading trl-0.28.0-py3-none-any.whl.metadata (11 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: datasets>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from trl) (4.4.2)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.0rc2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (4.57.1)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.8.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.6.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.20.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.1rc0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=3.0.0->trl) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Downloading trl-0.28.0-py3-none-any.whl (540 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 540.5/540.5 kB 10.5 MB/s eta 0:00:00a 0:00:01
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 28.6 MB/s eta 0:00:00:00:0100:01
Installing collected packages: bitsandbytes, trl
Successfully installed bitsandbytes-0.49.2 trl-0.28.0

In [4]:
!pip install -q --upgrade transformers datasets peft accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 82.4 MB/s eta 0:00:00:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 35.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.0/557.0 kB 32.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.9/380.9 kB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.3/553.3 kB 38.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.1.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 5.2.0 which is incompatible.
gradio 5.49.1 requires pydantic<2.12,>=2.0, but you have pydantic 2.12.5 which is incompatible.

In [ ]:
import huggingface_hub
import os
hf_token = os.getenv("hf_token")

huggingface_hub.login(token = hf_token)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import os
import gc
import json
import torch
import optuna
import random
import numpy as np

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    TrainerCallback,
)

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training


# ================= CONFIG =================
BASE_MODEL = "meta-llama/Llama-2-7b-chat-hf"
DATASET_FILE = "/kaggle/input/datasets/pradippokhrel45/coding-problem-of-alpaca-and-flytech-only/refined_train.jsonl"
OUTPUT_DIR = "./optuna_results"

MAX_LENGTH = 512
SEED = 42
N_TRIALS = 45

TRAIN_SUBSET_RATIO = 0.05
VAL_RATIO = 0.2


# ================= SEED =================
def set_seed(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed()


# ================= LOAD DATA =================
print("[DEBUG] Loading dataset...")

full_dataset = load_dataset(
    "json",
    data_files=DATASET_FILE,
    split="train"
)

print("[DEBUG] Dataset size:", len(full_dataset))


subset_size = int(len(full_dataset) * TRAIN_SUBSET_RATIO)

subset_dataset = (
    full_dataset
    .shuffle(seed=SEED)
    .select(range(subset_size))
)

print("[DEBUG] Subset size:", len(subset_dataset))


val_size = int(len(subset_dataset) * VAL_RATIO)

train_size = len(subset_dataset) - val_size

train_ds = subset_dataset.select(range(train_size))
val_ds = subset_dataset.select(range(train_size, train_size + val_size))

print("[DEBUG] Train size:", len(train_ds))
print("[DEBUG] Val size:", len(val_ds))


# ================= TOKENIZER =================
print("[DEBUG] Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"


# ================= TOKENIZATION (SFT MASKING) =================
def tokenize_fn(batch):

    input_ids_list = []
    labels_list = []
    attention_mask_list = []

    for prompt, code in zip(batch["prompt"], batch["code"]):

        prompt = str(prompt)
        code = str(code)

        # Full formatted instruction
        full_text = prompt + "\n" + code

        tokenized = tokenizer(
            full_text,
            truncation=True,
            padding="max_length",
            max_length=MAX_LENGTH
        )

        input_ids = tokenized["input_ids"]
        attention_mask = tokenized["attention_mask"]

        # Tokenize only prompt to mask it
        prompt_ids = tokenizer(
            prompt,
            truncation=True,
            max_length=MAX_LENGTH
        )["input_ids"]

        prompt_len = len(prompt_ids)

        labels = [-100] * len(input_ids)

        # Enable loss only on code tokens
        for i in range(prompt_len, len(input_ids)):
            if input_ids[i] != tokenizer.pad_token_id:
                labels[i] = input_ids[i]

        input_ids_list.append(input_ids)
        labels_list.append(labels)
        attention_mask_list.append(attention_mask)

    return {
        "input_ids": input_ids_list,
        "labels": labels_list,
        "attention_mask": attention_mask_list
    }


print("[DEBUG] Tokenizing train dataset...")
train_ds = train_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=train_ds.column_names
)

print("[DEBUG] Tokenizing val dataset...")
val_ds = val_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=val_ds.column_names
)


# ================= QUANT CONFIG =================
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True
)


# ================= OBJECTIVE =================
def objective(trial):

    print(f"\n========== STARTING TRIAL {trial.number} ==========")

    lr = trial.suggest_float("learning_rate", 8e-6, 3e-5, log=True)

    scheduler = trial.suggest_categorical(
        "lr_scheduler",
        ["linear", "cosine", "cosine_with_restarts"]
    )

    lora_r = trial.suggest_categorical("lora_r", [8, 16, 32])

    lora_alpha = trial.suggest_categorical("lora_alpha", [8, 16, 32])

    lora_dropout = trial.suggest_float("lora_dropout", 0.05, 0.15)

    batch_size = trial.suggest_categorical("batch_size", [4, 8,16])

    warmup_ratio = trial.suggest_float("warmup_ratio", 0.03, 0.15)

    print("[DEBUG] Hyperparameters:", {
        "lr": lr,
        "scheduler": scheduler,
        "r": lora_r,
        "alpha": lora_alpha,
        "dropout": lora_dropout,
        "batch": batch_size,
        "warmup": warmup_ratio
    })


    gc.collect()
    torch.cuda.empty_cache()


    try:

        # ========== Load Model ==========
        print("[DEBUG] Loading model...")

        model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL,
            quantization_config=bnb_config,
            device_map="auto"
        )

        model = prepare_model_for_kbit_training(model)

        print("[DEBUG] Model loaded")


        # ========== LoRA ==========
        print("[DEBUG] Applying LoRA...")

        lora_config = LoraConfig(
            r=lora_r,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            bias="none",
            task_type="CAUSAL_LM",
            target_modules=[
                "q_proj",
                "k_proj",
                "v_proj",
                "o_proj",
                "gate_proj",
                "up_proj",
                "down_proj"
            ]
        )

        model = get_peft_model(model, lora_config)

        model.print_trainable_parameters()

        total_steps = int(
            len(train_ds)
            / (batch_size * 4)
            * 2
        )

        warmup_steps = int(total_steps * warmup_ratio)

        print("[DEBUG] Total steps:", total_steps)
        print("[DEBUG] Warmup steps:", warmup_steps)


        # ========== Training Args ==========
        print("[DEBUG] Building TrainingArguments...")

        args = TrainingArguments(

            output_dir=f"{OUTPUT_DIR}/trial_{trial.number}",

            num_train_epochs=2,

            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,

            gradient_accumulation_steps=4,

            learning_rate=lr,

            lr_scheduler_type=scheduler,

            warmup_steps=warmup_steps,

            logging_steps=50,

            save_strategy="no",

            bf16=False,
            fp16=True,

            weight_decay=0.01,

            max_grad_norm=1.0,

            report_to="none",

            seed=SEED,

            remove_unused_columns=False,
        )


        # ========== Trainer ==========
        print("[DEBUG] Initializing Trainer...")

        trainer = Trainer(

            model=model,

            args=args,

            train_dataset=train_ds,

            eval_dataset=val_ds,
        )


        # ========== Train ==========
        print("[DEBUG] Starting training...")

        train_result = trainer.train()

        print("[DEBUG] Training finished")

        loss = train_result.training_loss

        print("[DEBUG] Training loss:", loss)

        if loss is None or np.isnan(loss) or np.isinf(loss):
            print("[ERROR] Invalid training loss")
            return float("inf")


        # ========== Eval ==========
        print("[DEBUG] Starting evaluation...")

        metrics = trainer.evaluate()

        print("[DEBUG] Eval metrics:", metrics)

        val_loss = metrics.get("eval_loss", None)

        print("[DEBUG] Validation loss:", val_loss)

        if val_loss is None or np.isnan(val_loss) or np.isinf(val_loss):
            print("[ERROR] Invalid validation loss")
            return float("inf")


    except Exception as e:

        print(f"[FATAL ERROR] Trial {trial.number} crashed:", str(e))

        if "model" in locals():
            del model

        if "trainer" in locals():
            del trainer

        gc.collect()
        torch.cuda.empty_cache()

        return float("inf")


    del model
    del trainer

    gc.collect()
    torch.cuda.empty_cache()

    print(f"[DEBUG] Trial {trial.number} finished successfully")

    return val_loss



# ================= MAIN =================
def main():

    sampler = optuna.samplers.TPESampler(
        seed=SEED,
        multivariate=True
    )

    pruner = optuna.pruners.MedianPruner(
        n_startup_trials=5,
        n_warmup_steps=1
    )


    study = optuna.create_study(

        direction="minimize",

        sampler=sampler,

        pruner=pruner,

        study_name="llama2_qlora_safe",

        storage="sqlite:///optuna1.db",

        load_if_exists=True
    )


    print("[DEBUG] Starting Optuna optimization...")

    study.optimize(objective, n_trials=N_TRIALS)


    best = study.best_trial


    print("\n========== BEST TRIAL ==========")

    print("Value:", best.value)

    print("\nParams:")

    for k, v in best.params.items():
        print(f"{k}: {v}")


    with open("best_params.json", "w") as f:
        json.dump(best.params, f, indent=4)


# ================= RUN =================
if __name__ == "__main__":

    main()

[DEBUG] Loading dataset...

Generating train split: 0 examples [00:00, ? examples/s]

[DEBUG] Dataset size: 12522
[DEBUG] Subset size: 626
[DEBUG] Train size: 501
[DEBUG] Val size: 125
[DEBUG] Loading tokenizer...

config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

[DEBUG] Tokenizing train dataset...

Map:   0%|          | 0/501 [00:00<?, ? examples/s]

[DEBUG] Tokenizing val dataset...

Map:   0%|          | 0/125 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-02-24 03:17:12,005] Using an existing study with name 'llama2_qlora_safe' instead of creating a new one.

[DEBUG] Starting Optuna optimization...

========== STARTING TRIAL 24 ==========
[DEBUG] Hyperparameters: {'lr': 1.3200005302792882e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 32, 'dropout': 0.053853409832070376, 'batch': 4, 'warmup': 0.04865509275066468}
[DEBUG] Loading model...

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 3
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8445177227258682
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6649800539016724, 'eval_runtime': 76.0489, 'eval_samples_per_second': 1.644, 'eval_steps_per_second': 0.421, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6649800539016724
[DEBUG] Trial 24 finished successfully

[I 2026-02-24 03:49:38,351] Trial 24 finished with value: 0.6649800539016724 and parameters: {'learning_rate': 1.3200005302792882e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.053853409832070376, 'batch_size': 4, 'warmup_ratio': 0.04865509275066468}. Best is trial 21 with value: 0.6157774329185486.

========== STARTING TRIAL 25 ==========
[DEBUG] Hyperparameters: {'lr': 2.083075572824991e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 32, 'dropout': 0.11637609771363153, 'batch': 4, 'warmup': 0.04649007089665136}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7359586209058762
[DEBUG] Starting evaluation...

[I 2026-02-24 04:22:17,599] Trial 25 finished with value: 0.6110676527023315 and parameters: {'learning_rate': 2.083075572824991e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.11637609771363153, 'batch_size': 4, 'warmup_ratio': 0.04649007089665136}. Best is trial 25 with value: 0.6110676527023315.

[DEBUG] Eval metrics: {'eval_loss': 0.6110676527023315, 'eval_runtime': 81.7472, 'eval_samples_per_second': 1.529, 'eval_steps_per_second': 0.391, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6110676527023315
[DEBUG] Trial 25 finished successfully

========== STARTING TRIAL 26 ==========
[DEBUG] Hyperparameters: {'lr': 1.8835535188421532e-05, 'scheduler': 'cosine_with_restarts', 'r': 8, 'alpha': 32, 'dropout': 0.11046880269602395, 'batch': 4, 'warmup': 0.07494054436633651}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 4
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7611954510211945
[DEBUG] Starting evaluation...

[I 2026-02-24 04:54:47,549] Trial 26 finished with value: 0.6201386451721191 and parameters: {'learning_rate': 1.8835535188421532e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.11046880269602395, 'batch_size': 4, 'warmup_ratio': 0.07494054436633651}. Best is trial 25 with value: 0.6110676527023315.

[DEBUG] Eval metrics: {'eval_loss': 0.6201386451721191, 'eval_runtime': 81.1919, 'eval_samples_per_second': 1.54, 'eval_steps_per_second': 0.394, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6201386451721191
[DEBUG] Trial 26 finished successfully

========== STARTING TRIAL 27 ==========
[DEBUG] Hyperparameters: {'lr': 1.5334570533031378e-05, 'scheduler': 'cosine_with_restarts', 'r': 8, 'alpha': 32, 'dropout': 0.13040512201354232, 'batch': 4, 'warmup': 0.08708541113280373}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 5
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8055131584405899
[DEBUG] Starting evaluation...

[I 2026-02-24 05:27:18,239] Trial 27 finished with value: 0.6453078985214233 and parameters: {'learning_rate': 1.5334570533031378e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.13040512201354232, 'batch_size': 4, 'warmup_ratio': 0.08708541113280373}. Best is trial 25 with value: 0.6110676527023315.

[DEBUG] Eval metrics: {'eval_loss': 0.6453078985214233, 'eval_runtime': 81.8001, 'eval_samples_per_second': 1.528, 'eval_steps_per_second': 0.391, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6453078985214233
[DEBUG] Trial 27 finished successfully

========== STARTING TRIAL 28 ==========
[DEBUG] Hyperparameters: {'lr': 2.510066515022361e-05, 'scheduler': 'cosine_with_restarts', 'r': 8, 'alpha': 32, 'dropout': 0.10928252621808496, 'batch': 4, 'warmup': 0.03325896112640083}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.708033487200737
[DEBUG] Starting evaluation...

[I 2026-02-24 05:59:48,841] Trial 28 finished with value: 0.5956746935844421 and parameters: {'learning_rate': 2.510066515022361e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.10928252621808496, 'batch_size': 4, 'warmup_ratio': 0.03325896112640083}. Best is trial 28 with value: 0.5956746935844421.

[DEBUG] Eval metrics: {'eval_loss': 0.5956746935844421, 'eval_runtime': 81.4151, 'eval_samples_per_second': 1.535, 'eval_steps_per_second': 0.393, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5956746935844421
[DEBUG] Trial 28 finished successfully

========== STARTING TRIAL 29 ==========
[DEBUG] Hyperparameters: {'lr': 2.8988802606233215e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.11338059675214027, 'batch': 4, 'warmup': 0.046697630964238436}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.6898881122469902
[DEBUG] Starting evaluation...

[I 2026-02-24 06:32:19,463] Trial 29 finished with value: 0.586391031742096 and parameters: {'learning_rate': 2.8988802606233215e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.11338059675214027, 'batch_size': 4, 'warmup_ratio': 0.046697630964238436}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.586391031742096, 'eval_runtime': 81.1633, 'eval_samples_per_second': 1.54, 'eval_steps_per_second': 0.394, 'epoch': 2.0}
[DEBUG] Validation loss: 0.586391031742096
[DEBUG] Trial 29 finished successfully

========== STARTING TRIAL 30 ==========
[DEBUG] Hyperparameters: {'lr': 2.3613881380130124e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 32, 'dropout': 0.11023746456633202, 'batch': 4, 'warmup': 0.033968883812377615}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7173387259244919
[DEBUG] Starting evaluation...

[I 2026-02-24 07:04:51,186] Trial 30 finished with value: 0.6001039147377014 and parameters: {'learning_rate': 2.3613881380130124e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.11023746456633202, 'batch_size': 4, 'warmup_ratio': 0.033968883812377615}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.6001039147377014, 'eval_runtime': 81.2319, 'eval_samples_per_second': 1.539, 'eval_steps_per_second': 0.394, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6001039147377014
[DEBUG] Trial 30 finished successfully

========== STARTING TRIAL 31 ==========
[DEBUG] Hyperparameters: {'lr': 2.974912826231461e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.0986139996969155, 'batch': 16, 'warmup': 0.04008410026946922}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 0
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.9905774593353271
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.8538931012153625, 'eval_runtime': 67.8767, 'eval_samples_per_second': 1.842, 'eval_steps_per_second': 0.118, 'epoch': 2.0}
[DEBUG] Validation loss: 0.8538931012153625

[I 2026-02-24 07:34:26,381] Trial 31 finished with value: 0.8538931012153625 and parameters: {'learning_rate': 2.974912826231461e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.0986139996969155, 'batch_size': 16, 'warmup_ratio': 0.04008410026946922}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Trial 31 finished successfully

========== STARTING TRIAL 32 ==========
[DEBUG] Hyperparameters: {'lr': 2.8576726834678702e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 8, 'dropout': 0.12529465774925755, 'batch': 4, 'warmup': 0.05075006139941184}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 3
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.857356920838356
[DEBUG] Starting evaluation...

[I 2026-02-24 08:07:15,260] Trial 32 finished with value: 0.6734612584114075 and parameters: {'learning_rate': 2.8576726834678702e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 8, 'lora_dropout': 0.12529465774925755, 'batch_size': 4, 'warmup_ratio': 0.05075006139941184}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.6734612584114075, 'eval_runtime': 82.3532, 'eval_samples_per_second': 1.518, 'eval_steps_per_second': 0.389, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6734612584114075
[DEBUG] Trial 32 finished successfully

========== STARTING TRIAL 33 ==========
[DEBUG] Hyperparameters: {'lr': 2.428026451778549e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 32, 'dropout': 0.12710391656983194, 'batch': 4, 'warmup': 0.03575317382216855}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7136672288179398
[DEBUG] Starting evaluation...

[I 2026-02-24 08:39:58,831] Trial 33 finished with value: 0.5980474948883057 and parameters: {'learning_rate': 2.428026451778549e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.12710391656983194, 'batch_size': 4, 'warmup_ratio': 0.03575317382216855}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.5980474948883057, 'eval_runtime': 81.1382, 'eval_samples_per_second': 1.541, 'eval_steps_per_second': 0.394, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5980474948883057
[DEBUG] Trial 33 finished successfully

========== STARTING TRIAL 34 ==========
[DEBUG] Hyperparameters: {'lr': 2.7349783438601555e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 32, 'dropout': 0.14867368911569373, 'batch': 4, 'warmup': 0.035156326138041795}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.6977490037679672
[DEBUG] Starting evaluation...

[I 2026-02-24 09:12:32,294] Trial 34 finished with value: 0.5890582799911499 and parameters: {'learning_rate': 2.7349783438601555e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.14867368911569373, 'batch_size': 4, 'warmup_ratio': 0.035156326138041795}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.5890582799911499, 'eval_runtime': 81.4362, 'eval_samples_per_second': 1.535, 'eval_steps_per_second': 0.393, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5890582799911499
[DEBUG] Trial 34 finished successfully

========== STARTING TRIAL 35 ==========
[DEBUG] Hyperparameters: {'lr': 2.8005366621727287e-05, 'scheduler': 'linear', 'r': 16, 'alpha': 32, 'dropout': 0.13628817947182015, 'batch': 8, 'warmup': 0.03457841621200675}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8396211266517639
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6602548956871033, 'eval_runtime': 71.1489, 'eval_samples_per_second': 1.757, 'eval_steps_per_second': 0.225, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6602548956871033

[I 2026-02-24 09:43:06,762] Trial 35 finished with value: 0.6602548956871033 and parameters: {'learning_rate': 2.8005366621727287e-05, 'lr_scheduler': 'linear', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.13628817947182015, 'batch_size': 8, 'warmup_ratio': 0.03457841621200675}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Trial 35 finished successfully

========== STARTING TRIAL 36 ==========
[DEBUG] Hyperparameters: {'lr': 2.4124542854178288e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.14795644063323532, 'batch': 8, 'warmup': 0.05087204717662463}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8594427108764648
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6894927024841309, 'eval_runtime': 71.1041, 'eval_samples_per_second': 1.758, 'eval_steps_per_second': 0.225, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6894927024841309

[I 2026-02-24 10:13:36,528] Trial 36 finished with value: 0.6894927024841309 and parameters: {'learning_rate': 2.4124542854178288e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.14795644063323532, 'batch_size': 8, 'warmup_ratio': 0.05087204717662463}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Trial 36 finished successfully

========== STARTING TRIAL 37 ==========
[DEBUG] Hyperparameters: {'lr': 2.2262653268360625e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 32, 'dropout': 0.14646755715284934, 'batch': 4, 'warmup': 0.05240460751963785}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 3
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7315035760402679
[DEBUG] Starting evaluation...

[I 2026-02-24 10:46:10,038] Trial 37 finished with value: 0.6053628921508789 and parameters: {'learning_rate': 2.2262653268360625e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.14646755715284934, 'batch_size': 4, 'warmup_ratio': 0.05240460751963785}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.6053628921508789, 'eval_runtime': 81.2594, 'eval_samples_per_second': 1.538, 'eval_steps_per_second': 0.394, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6053628921508789
[DEBUG] Trial 37 finished successfully

========== STARTING TRIAL 38 ==========
[DEBUG] Hyperparameters: {'lr': 2.625157232135307e-05, 'scheduler': 'cosine_with_restarts', 'r': 16, 'alpha': 16, 'dropout': 0.11962175991698364, 'batch': 4, 'warmup': 0.04975760771455761}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 3
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7819100618362427
[DEBUG] Starting evaluation...

[I 2026-02-24 11:19:19,648] Trial 38 finished with value: 0.6298055052757263 and parameters: {'learning_rate': 2.625157232135307e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 16, 'lora_alpha': 16, 'lora_dropout': 0.11962175991698364, 'batch_size': 4, 'warmup_ratio': 0.04975760771455761}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.6298055052757263, 'eval_runtime': 81.5917, 'eval_samples_per_second': 1.532, 'eval_steps_per_second': 0.392, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6298055052757263
[DEBUG] Trial 38 finished successfully

========== STARTING TRIAL 39 ==========
[DEBUG] Hyperparameters: {'lr': 2.5765931740776575e-05, 'scheduler': 'linear', 'r': 8, 'alpha': 32, 'dropout': 0.1027201107001482, 'batch': 4, 'warmup': 0.03400798617006224}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7120707631111145
[DEBUG] Starting evaluation...

[I 2026-02-24 11:52:03,483] Trial 39 finished with value: 0.5932674407958984 and parameters: {'learning_rate': 2.5765931740776575e-05, 'lr_scheduler': 'linear', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.1027201107001482, 'batch_size': 4, 'warmup_ratio': 0.03400798617006224}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.5932674407958984, 'eval_runtime': 81.4921, 'eval_samples_per_second': 1.534, 'eval_steps_per_second': 0.393, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5932674407958984
[DEBUG] Trial 39 finished successfully

========== STARTING TRIAL 40 ==========
[DEBUG] Hyperparameters: {'lr': 2.771167241168848e-05, 'scheduler': 'linear', 'r': 8, 'alpha': 32, 'dropout': 0.08926107177221834, 'batch': 4, 'warmup': 0.03359876993517523}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7017453536391258
[DEBUG] Starting evaluation...

[I 2026-02-24 12:24:47,808] Trial 40 finished with value: 0.5879229307174683 and parameters: {'learning_rate': 2.771167241168848e-05, 'lr_scheduler': 'linear', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.08926107177221834, 'batch_size': 4, 'warmup_ratio': 0.03359876993517523}. Best is trial 29 with value: 0.586391031742096.

[DEBUG] Eval metrics: {'eval_loss': 0.5879229307174683, 'eval_runtime': 81.5164, 'eval_samples_per_second': 1.533, 'eval_steps_per_second': 0.393, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5879229307174683
[DEBUG] Trial 40 finished successfully

========== STARTING TRIAL 41 ==========
[DEBUG] Hyperparameters: {'lr': 2.8744695687112865e-05, 'scheduler': 'linear', 'r': 8, 'alpha': 32, 'dropout': 0.0810940305392357, 'batch': 4, 'warmup': 0.04042500026503622}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.6965994611382484
[DEBUG] Starting evaluation...

[I 2026-02-24 12:58:03,480] Trial 41 finished with value: 0.5851140022277832 and parameters: {'learning_rate': 2.8744695687112865e-05, 'lr_scheduler': 'linear', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.0810940305392357, 'batch_size': 4, 'warmup_ratio': 0.04042500026503622}. Best is trial 41 with value: 0.5851140022277832.

[DEBUG] Eval metrics: {'eval_loss': 0.5851140022277832, 'eval_runtime': 82.7069, 'eval_samples_per_second': 1.511, 'eval_steps_per_second': 0.387, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5851140022277832
[DEBUG] Trial 41 finished successfully

========== STARTING TRIAL 42 ==========
[DEBUG] Hyperparameters: {'lr': 2.5179901070415928e-05, 'scheduler': 'linear', 'r': 8, 'alpha': 32, 'dropout': 0.08486071812251815, 'batch': 4, 'warmup': 0.03989659479491788}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7150778919458389
[DEBUG] Starting evaluation...

[I 2026-02-24 13:31:17,770] Trial 42 finished with value: 0.5948429703712463 and parameters: {'learning_rate': 2.5179901070415928e-05, 'lr_scheduler': 'linear', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.08486071812251815, 'batch_size': 4, 'warmup_ratio': 0.03989659479491788}. Best is trial 41 with value: 0.5851140022277832.

[DEBUG] Eval metrics: {'eval_loss': 0.5948429703712463, 'eval_runtime': 82.6467, 'eval_samples_per_second': 1.512, 'eval_steps_per_second': 0.387, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5948429703712463
[DEBUG] Trial 42 finished successfully

========== STARTING TRIAL 43 ==========
[DEBUG] Hyperparameters: {'lr': 2.969471439360311e-05, 'scheduler': 'linear', 'r': 16, 'alpha': 8, 'dropout': 0.10765895902872755, 'batch': 4, 'warmup': 0.03358036932187594}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8636632561683655
[DEBUG] Starting evaluation...

[I 2026-02-24 14:04:00,246] Trial 43 finished with value: 0.6658046841621399 and parameters: {'learning_rate': 2.969471439360311e-05, 'lr_scheduler': 'linear', 'lora_r': 16, 'lora_alpha': 8, 'lora_dropout': 0.10765895902872755, 'batch_size': 4, 'warmup_ratio': 0.03358036932187594}. Best is trial 41 with value: 0.5851140022277832.

[DEBUG] Eval metrics: {'eval_loss': 0.6658046841621399, 'eval_runtime': 81.6831, 'eval_samples_per_second': 1.53, 'eval_steps_per_second': 0.392, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6658046841621399
[DEBUG] Trial 43 finished successfully

========== STARTING TRIAL 44 ==========
[DEBUG] Hyperparameters: {'lr': 2.9089891826881823e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.096107628615683, 'batch': 4, 'warmup': 0.06934415060563733}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 4
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.698545403778553
[DEBUG] Starting evaluation...

[I 2026-02-24 14:36:39,366] Trial 44 finished with value: 0.5847010612487793 and parameters: {'learning_rate': 2.9089891826881823e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.096107628615683, 'batch_size': 4, 'warmup_ratio': 0.06934415060563733}. Best is trial 44 with value: 0.5847010612487793.

[DEBUG] Eval metrics: {'eval_loss': 0.5847010612487793, 'eval_runtime': 82.532, 'eval_samples_per_second': 1.515, 'eval_steps_per_second': 0.388, 'epoch': 2.0}
[DEBUG] Validation loss: 0.5847010612487793
[DEBUG] Trial 44 finished successfully

========== STARTING TRIAL 45 ==========
[DEBUG] Hyperparameters: {'lr': 2.8819354967941576e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.09370724400539303, 'batch': 4, 'warmup': 0.09601415533821651}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 5
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7046886757016182
[DEBUG] Starting evaluation...

[I 2026-02-24 15:09:27,926] Trial 45 finished with value: 0.585334300994873 and parameters: {'learning_rate': 2.8819354967941576e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.09370724400539303, 'batch_size': 4, 'warmup_ratio': 0.09601415533821651}. Best is trial 44 with value: 0.5847010612487793.

[DEBUG] Eval metrics: {'eval_loss': 0.585334300994873, 'eval_runtime': 82.2733, 'eval_samples_per_second': 1.519, 'eval_steps_per_second': 0.389, 'epoch': 2.0}
[DEBUG] Validation loss: 0.585334300994873
[DEBUG] Trial 45 finished successfully

========== STARTING TRIAL 46 ==========
[DEBUG] Hyperparameters: {'lr': 2.5993835219092706e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.09701785089929542, 'batch': 4, 'warmup': 0.12908368137757054}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 8
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
[W 2026-02-24 15:09:56,098] Trial 46 failed with parameters: {'learning_rate': 2.5993835219092706e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.09701785089929542, 'batch_size': 4, 'warmup_ratio': 0.12908368137757054} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_55/2662111403.py", line 311, in objective
    train_result = trainer.train()
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 1412, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 1742, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 1979, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/accelerate/accelerator.py", line 2848, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/_tensor.py", line 647, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.12/dist-packages/torch/autograd/__init__.py", line 354, in backward
    _engine_run_backward(
  File "/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py", line 829, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-02-24 15:09:56,113] Trial 46 failed with value None.

KeyboardInterrupt: