In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/pradippokhrel45/coding-problem-of-alpaca-and-flytech-only/refined_train.jsonl
/kaggle/input/datasets/pradippokhrel45/llama-2-fine-tuning-datasets-for-python-code/train.jsonl

In [2]:
!pip install trl bitsandbytes optuna accelerate

Collecting trl
  Downloading trl-0.28.0-py3-none-any.whl.metadata (11 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: datasets>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from trl) (4.4.2)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.0rc2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (4.57.1)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.8.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.6.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.20.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.1rc0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=3.0.0->trl) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=3.0.0->trl) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Downloading trl-0.28.0-py3-none-any.whl (540 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 540.5/540.5 kB 10.4 MB/s eta 0:00:00a 0:00:01
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 31.4 MB/s eta 0:00:00:00:0100:01
Installing collected packages: bitsandbytes, trl
Successfully installed bitsandbytes-0.49.2 trl-0.28.0

In [3]:
!pip install -q --upgrade transformers datasets peft accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 78.5 MB/s eta 0:00:00:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 33.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.0/557.0 kB 33.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.9/380.9 kB 26.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.3/553.3 kB 31.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.1.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 5.2.0 which is incompatible.
gradio 5.49.1 requires pydantic<2.12,>=2.0, but you have pydantic 2.12.5 which is incompatible.

In [ ]:
import huggingface_hub
import os
hf_token = os.getenv("hf_token")

huggingface_hub.login(token = hf_token)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import os
import gc
import json
import torch
import optuna
import random
import numpy as np

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    TrainerCallback,
)

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training


# ================= CONFIG =================
BASE_MODEL = "meta-llama/Llama-2-7b-chat-hf"
DATASET_FILE = "/kaggle/input/datasets/pradippokhrel45/coding-problem-of-alpaca-and-flytech-only/refined_train.jsonl"
OUTPUT_DIR = "./optuna_results"

MAX_LENGTH = 512
SEED = 42
N_TRIALS = 40

TRAIN_SUBSET_RATIO = 0.05
VAL_RATIO = 0.2


# ================= SEED =================
def set_seed(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


set_seed()


# ================= LOAD DATA =================
print("[DEBUG] Loading dataset...")

full_dataset = load_dataset(
    "json",
    data_files=DATASET_FILE,
    split="train"
)

print("[DEBUG] Dataset size:", len(full_dataset))


subset_size = int(len(full_dataset) * TRAIN_SUBSET_RATIO)

subset_dataset = (
    full_dataset
    .shuffle(seed=SEED)
    .select(range(subset_size))
)

print("[DEBUG] Subset size:", len(subset_dataset))


val_size = int(len(subset_dataset) * VAL_RATIO)

train_size = len(subset_dataset) - val_size

train_ds = subset_dataset.select(range(train_size))
val_ds = subset_dataset.select(range(train_size, train_size + val_size))

print("[DEBUG] Train size:", len(train_ds))
print("[DEBUG] Val size:", len(val_ds))


# ================= TOKENIZER =================
print("[DEBUG] Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"


# ================= TOKENIZATION (SFT MASKING) =================
def tokenize_fn(batch):

    input_ids_list = []
    labels_list = []
    attention_mask_list = []

    for prompt, code in zip(batch["prompt"], batch["code"]):

        prompt = str(prompt)
        code = str(code)

        # Full formatted instruction
        full_text = prompt + "\n" + code

        tokenized = tokenizer(
            full_text,
            truncation=True,
            padding="max_length",
            max_length=MAX_LENGTH
        )

        input_ids = tokenized["input_ids"]
        attention_mask = tokenized["attention_mask"]

        # Tokenize only prompt to mask it
        prompt_ids = tokenizer(
            prompt,
            truncation=True,
            max_length=MAX_LENGTH
        )["input_ids"]

        prompt_len = len(prompt_ids)

        labels = [-100] * len(input_ids)

        # Enable loss only on code tokens
        for i in range(prompt_len, len(input_ids)):
            if input_ids[i] != tokenizer.pad_token_id:
                labels[i] = input_ids[i]

        input_ids_list.append(input_ids)
        labels_list.append(labels)
        attention_mask_list.append(attention_mask)

    return {
        "input_ids": input_ids_list,
        "labels": labels_list,
        "attention_mask": attention_mask_list
    }


print("[DEBUG] Tokenizing train dataset...")
train_ds = train_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=train_ds.column_names
)

print("[DEBUG] Tokenizing val dataset...")
val_ds = val_ds.map(
    tokenize_fn,
    batched=True,
    remove_columns=val_ds.column_names
)


# ================= QUANT CONFIG =================
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True
)


# ================= OBJECTIVE =================
def objective(trial):

    print(f"\n========== STARTING TRIAL {trial.number} ==========")

    lr = trial.suggest_float("learning_rate", 8e-6, 3e-5, log=True)

    scheduler = trial.suggest_categorical(
        "lr_scheduler",
        ["linear", "cosine", "cosine_with_restarts"]
    )

    lora_r = trial.suggest_categorical("lora_r", [8, 16, 32])

    lora_alpha = trial.suggest_categorical("lora_alpha", [8, 16, 32])

    lora_dropout = trial.suggest_float("lora_dropout", 0.05, 0.15)

    batch_size = trial.suggest_categorical("batch_size", [4, 8,16])

    warmup_ratio = trial.suggest_float("warmup_ratio", 0.03, 0.15)

    print("[DEBUG] Hyperparameters:", {
        "lr": lr,
        "scheduler": scheduler,
        "r": lora_r,
        "alpha": lora_alpha,
        "dropout": lora_dropout,
        "batch": batch_size,
        "warmup": warmup_ratio
    })


    gc.collect()
    torch.cuda.empty_cache()


    try:

        # ========== Load Model ==========
        print("[DEBUG] Loading model...")

        model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL,
            quantization_config=bnb_config,
            device_map="auto"
        )

        model = prepare_model_for_kbit_training(model)

        print("[DEBUG] Model loaded")


        # ========== LoRA ==========
        print("[DEBUG] Applying LoRA...")

        lora_config = LoraConfig(
            r=lora_r,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            bias="none",
            task_type="CAUSAL_LM",
            target_modules=[
                "q_proj",
                "k_proj",
                "v_proj",
                "o_proj",
                "gate_proj",
                "up_proj",
                "down_proj"
            ]
        )

        model = get_peft_model(model, lora_config)

        model.print_trainable_parameters()

        total_steps = int(
            len(train_ds)
            / (batch_size * 4)
            * 2
        )

        warmup_steps = int(total_steps * warmup_ratio)

        print("[DEBUG] Total steps:", total_steps)
        print("[DEBUG] Warmup steps:", warmup_steps)


        # ========== Training Args ==========
        print("[DEBUG] Building TrainingArguments...")

        args = TrainingArguments(

            output_dir=f"{OUTPUT_DIR}/trial_{trial.number}",

            num_train_epochs=2,

            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,

            gradient_accumulation_steps=4,

            learning_rate=lr,

            lr_scheduler_type=scheduler,

            warmup_steps=warmup_steps,

            logging_steps=50,

            save_strategy="no",

            bf16=False,
            fp16=True,

            weight_decay=0.01,

            max_grad_norm=1.0,

            report_to="none",

            seed=SEED,

            remove_unused_columns=False,
        )


        # ========== Trainer ==========
        print("[DEBUG] Initializing Trainer...")

        trainer = Trainer(

            model=model,

            args=args,

            train_dataset=train_ds,

            eval_dataset=val_ds,
        )


        # ========== Train ==========
        print("[DEBUG] Starting training...")

        train_result = trainer.train()

        print("[DEBUG] Training finished")

        loss = train_result.training_loss

        print("[DEBUG] Training loss:", loss)

        if loss is None or np.isnan(loss) or np.isinf(loss):
            print("[ERROR] Invalid training loss")
            return float("inf")


        # ========== Eval ==========
        print("[DEBUG] Starting evaluation...")

        metrics = trainer.evaluate()

        print("[DEBUG] Eval metrics:", metrics)

        val_loss = metrics.get("eval_loss", None)

        print("[DEBUG] Validation loss:", val_loss)

        if val_loss is None or np.isnan(val_loss) or np.isinf(val_loss):
            print("[ERROR] Invalid validation loss")
            return float("inf")


    except Exception as e:

        print(f"[FATAL ERROR] Trial {trial.number} crashed:", str(e))

        if "model" in locals():
            del model

        if "trainer" in locals():
            del trainer

        gc.collect()
        torch.cuda.empty_cache()

        return float("inf")


    del model
    del trainer

    gc.collect()
    torch.cuda.empty_cache()

    print(f"[DEBUG] Trial {trial.number} finished successfully")

    return val_loss



# ================= MAIN =================
def main():

    sampler = optuna.samplers.TPESampler(
        seed=SEED,
        multivariate=True
    )

    pruner = optuna.pruners.MedianPruner(
        n_startup_trials=5,
        n_warmup_steps=1
    )


    study = optuna.create_study(

        direction="minimize",

        sampler=sampler,

        pruner=pruner,

        study_name="llama2_qlora_safe",

        storage="sqlite:///optuna1.db",

        load_if_exists=False
    )


    print("[DEBUG] Starting Optuna optimization...")

    study.optimize(objective, n_trials=N_TRIALS)


    best = study.best_trial


    print("\n========== BEST TRIAL ==========")

    print("Value:", best.value)

    print("\nParams:")

    for k, v in best.params.items():
        print(f"{k}: {v}")


    with open("best_params.json", "w") as f:
        json.dump(best.params, f, indent=4)


# ================= RUN =================
if __name__ == "__main__":

    main()

[DEBUG] Loading dataset...

Generating train split: 0 examples [00:00, ? examples/s]

[DEBUG] Dataset size: 12522
[DEBUG] Subset size: 626
[DEBUG] Train size: 501
[DEBUG] Val size: 125
[DEBUG] Loading tokenizer...

config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

[DEBUG] Tokenizing train dataset...

Map:   0%|          | 0/501 [00:00<?, ? examples/s]

[DEBUG] Tokenizing val dataset...

Map:   0%|          | 0/125 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-02-23 14:30:38,627] A new study created in RDB with name: llama2_qlora_safe

[DEBUG] Starting Optuna optimization...

========== STARTING TRIAL 0 ==========
[DEBUG] Hyperparameters: {'lr': 1.3124649863747118e-05, 'scheduler': 'linear', 'r': 8, 'alpha': 8, 'dropout': 0.052058449429580246, 'batch': 4, 'warmup': 0.051818996064852074}
[DEBUG] Loading model...

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 3
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1225752979516983
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.0179308652877808, 'eval_runtime': 80.2049, 'eval_samples_per_second': 1.559, 'eval_steps_per_second': 0.399, 'epoch': 2.0}
[DEBUG] Validation loss: 1.0179308652877808

[I 2026-02-23 15:03:30,182] Trial 0 finished with value: 1.0179308652877808 and parameters: {'learning_rate': 1.3124649863747118e-05, 'lr_scheduler': 'linear', 'lora_r': 8, 'lora_alpha': 8, 'lora_dropout': 0.052058449429580246, 'batch_size': 4, 'warmup_ratio': 0.051818996064852074}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 0 finished successfully

========== STARTING TRIAL 1 ==========
[DEBUG] Hyperparameters: {'lr': 1.019459342774817e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 32, 'dropout': 0.12851759613930136, 'batch': 16, 'warmup': 0.035574049526399726}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 0
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1900207996368408
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.133636713027954, 'eval_runtime': 64.6124, 'eval_samples_per_second': 1.935, 'eval_steps_per_second': 0.124, 'epoch': 2.0}
[DEBUG] Validation loss: 1.133636713027954

[I 2026-02-23 15:31:35,703] Trial 1 finished with value: 1.133636713027954 and parameters: {'learning_rate': 1.019459342774817e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.12851759613930136, 'batch_size': 16, 'warmup_ratio': 0.035574049526399726}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 1 finished successfully

========== STARTING TRIAL 2 ==========
[DEBUG] Hyperparameters: {'lr': 1.7858284134411106e-05, 'scheduler': 'cosine_with_restarts', 'r': 8, 'alpha': 16, 'dropout': 0.06220382348447789, 'batch': 16, 'warmup': 0.06105359779200203}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 0
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1928772926330566
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.1340324878692627, 'eval_runtime': 72.0233, 'eval_samples_per_second': 1.736, 'eval_steps_per_second': 0.111, 'epoch': 2.0}
[DEBUG] Validation loss: 1.1340324878692627

[I 2026-02-23 15:59:59,343] Trial 2 finished with value: 1.1340324878692627 and parameters: {'learning_rate': 1.7858284134411106e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.06220382348447789, 'batch_size': 16, 'warmup_ratio': 0.06105359779200203}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 2 finished successfully

========== STARTING TRIAL 3 ==========
[DEBUG] Hyperparameters: {'lr': 1.920430053485884e-05, 'scheduler': 'cosine_with_restarts', 'r': 16, 'alpha': 8, 'dropout': 0.14218742350231167, 'batch': 8, 'warmup': 0.06903963969159171}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1740399599075317
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.1094290018081665, 'eval_runtime': 66.5233, 'eval_samples_per_second': 1.879, 'eval_steps_per_second': 0.241, 'epoch': 2.0}
[DEBUG] Validation loss: 1.1094290018081665

[I 2026-02-23 16:29:12,110] Trial 3 finished with value: 1.1094290018081665 and parameters: {'learning_rate': 1.920430053485884e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 16, 'lora_alpha': 8, 'lora_dropout': 0.14218742350231167, 'batch_size': 8, 'warmup_ratio': 0.06903963969159171}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 3 finished successfully

========== STARTING TRIAL 4 ==========
[DEBUG] Hyperparameters: {'lr': 1.3372201258639933e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 32, 'dropout': 0.12722447692966574, 'batch': 16, 'warmup': 0.11482288126171405}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.174484372138977
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.1006072759628296, 'eval_runtime': 70.1406, 'eval_samples_per_second': 1.782, 'eval_steps_per_second': 0.114, 'epoch': 2.0}
[DEBUG] Validation loss: 1.1006072759628296

[I 2026-02-23 16:57:22,146] Trial 4 finished with value: 1.1006072759628296 and parameters: {'learning_rate': 1.3372201258639933e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.12722447692966574, 'batch_size': 16, 'warmup_ratio': 0.11482288126171405}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 4 finished successfully

========== STARTING TRIAL 5 ==========
[DEBUG] Hyperparameters: {'lr': 2.0968284273613455e-05, 'scheduler': 'linear', 'r': 16, 'alpha': 8, 'dropout': 0.08251833220267471, 'batch': 16, 'warmup': 0.08666579101943392}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Eval metrics: {'eval_loss': 1.1971790790557861, 'eval_runtime': 64.657, 'eval_samples_per_second': 1.933, 'eval_steps_per_second': 0.124, 'epoch': 2.0}
[DEBUG] Validation loss: 1.1971790790557861

[I 2026-02-23 17:25:54,321] Trial 5 finished with value: 1.1971790790557861 and parameters: {'learning_rate': 2.0968284273613455e-05, 'lr_scheduler': 'linear', 'lora_r': 16, 'lora_alpha': 8, 'lora_dropout': 0.08251833220267471, 'batch_size': 16, 'warmup_ratio': 0.08666579101943392}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 5 finished successfully

========== STARTING TRIAL 6 ==========
[DEBUG] Hyperparameters: {'lr': 9.37002659609628e-06, 'scheduler': 'cosine', 'r': 8, 'alpha': 8, 'dropout': 0.053142918568673425, 'batch': 4, 'warmup': 0.13890797687113116}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 8
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1780972480773926
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.1143096685409546, 'eval_runtime': 81.9409, 'eval_samples_per_second': 1.525, 'eval_steps_per_second': 0.391, 'epoch': 2.0}
[DEBUG] Validation loss: 1.1143096685409546

[I 2026-02-23 17:57:18,179] Trial 6 finished with value: 1.1143096685409546 and parameters: {'learning_rate': 9.37002659609628e-06, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 8, 'lora_dropout': 0.053142918568673425, 'batch_size': 4, 'warmup_ratio': 0.13890797687113116}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 6 finished successfully

========== STARTING TRIAL 7 ==========
[DEBUG] Hyperparameters: {'lr': 1.1122221025856185e-05, 'scheduler': 'cosine', 'r': 16, 'alpha': 8, 'dropout': 0.13714605901877175, 'batch': 16, 'warmup': 0.09472106902987808}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 39,976,960 || all params: 6,778,392,576 || trainable%: 0.5898
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.27250337600708
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.2435815334320068, 'eval_runtime': 64.3891, 'eval_samples_per_second': 1.941, 'eval_steps_per_second': 0.124, 'epoch': 2.0}
[DEBUG] Validation loss: 1.2435815334320068

[I 2026-02-23 18:25:49,249] Trial 7 finished with value: 1.2435815334320068 and parameters: {'learning_rate': 1.1122221025856185e-05, 'lr_scheduler': 'cosine', 'lora_r': 16, 'lora_alpha': 8, 'lora_dropout': 0.13714605901877175, 'batch_size': 16, 'warmup_ratio': 0.09472106902987808}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 7 finished successfully

========== STARTING TRIAL 8 ==========
[DEBUG] Hyperparameters: {'lr': 2.325872387775092e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 8, 'dropout': 0.0917411003148779, 'batch': 16, 'warmup': 0.1431491644695023}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.2410300970077515
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.184023141860962, 'eval_runtime': 64.8207, 'eval_samples_per_second': 1.928, 'eval_steps_per_second': 0.123, 'epoch': 2.0}
[DEBUG] Validation loss: 1.184023141860962

[I 2026-02-23 18:53:52,833] Trial 8 finished with value: 1.184023141860962 and parameters: {'learning_rate': 2.325872387775092e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 8, 'lora_dropout': 0.0917411003148779, 'batch_size': 16, 'warmup_ratio': 0.1431491644695023}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 8 finished successfully

========== STARTING TRIAL 9 ==========
[DEBUG] Hyperparameters: {'lr': 1.2263616915515364e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 8, 'dropout': 0.053688694735453284, 'batch': 4, 'warmup': 0.06343757570839337}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 3
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1262658387422562
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.0438872575759888, 'eval_runtime': 73.9953, 'eval_samples_per_second': 1.689, 'eval_steps_per_second': 0.432, 'epoch': 2.0}
[DEBUG] Validation loss: 1.0438872575759888

[I 2026-02-23 19:25:47,345] Trial 9 finished with value: 1.0438872575759888 and parameters: {'learning_rate': 1.2263616915515364e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 8, 'lora_dropout': 0.053688694735453284, 'batch_size': 4, 'warmup_ratio': 0.06343757570839337}. Best is trial 0 with value: 1.0179308652877808.

[DEBUG] Trial 9 finished successfully

========== STARTING TRIAL 10 ==========
[DEBUG] Hyperparameters: {'lr': 1.9263960198528424e-05, 'scheduler': 'linear', 'r': 8, 'alpha': 8, 'dropout': 0.06262199042819183, 'batch': 4, 'warmup': 0.0332524854769901}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.0106386989355087
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.8273223042488098, 'eval_runtime': 81.4143, 'eval_samples_per_second': 1.535, 'eval_steps_per_second': 0.393, 'epoch': 2.0}
[DEBUG] Validation loss: 0.8273223042488098

[I 2026-02-23 19:57:11,895] Trial 10 finished with value: 0.8273223042488098 and parameters: {'learning_rate': 1.9263960198528424e-05, 'lr_scheduler': 'linear', 'lora_r': 8, 'lora_alpha': 8, 'lora_dropout': 0.06262199042819183, 'batch_size': 4, 'warmup_ratio': 0.0332524854769901}. Best is trial 10 with value: 0.8273223042488098.

[DEBUG] Trial 10 finished successfully

========== STARTING TRIAL 11 ==========
[DEBUG] Hyperparameters: {'lr': 1.605960199399902e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 32, 'dropout': 0.0726815966099835, 'batch': 4, 'warmup': 0.034922891634835196}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7956479638814926
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6383668184280396, 'eval_runtime': 74.3717, 'eval_samples_per_second': 1.681, 'eval_steps_per_second': 0.43, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6383668184280396

[I 2026-02-23 20:29:07,058] Trial 11 finished with value: 0.6383668184280396 and parameters: {'learning_rate': 1.605960199399902e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.0726815966099835, 'batch_size': 4, 'warmup_ratio': 0.034922891634835196}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 11 finished successfully

========== STARTING TRIAL 12 ==========
[DEBUG] Hyperparameters: {'lr': 2.0966084664789243e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 32, 'dropout': 0.08418581169657688, 'batch': 8, 'warmup': 0.05691044440990228}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.9194151759147644
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.7244914174079895, 'eval_runtime': 74.765, 'eval_samples_per_second': 1.672, 'eval_steps_per_second': 0.214, 'epoch': 2.0}
[DEBUG] Validation loss: 0.7244914174079895

[I 2026-02-23 20:58:23,055] Trial 12 finished with value: 0.7244914174079895 and parameters: {'learning_rate': 2.0966084664789243e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.08418581169657688, 'batch_size': 8, 'warmup_ratio': 0.05691044440990228}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 12 finished successfully

========== STARTING TRIAL 13 ==========
[DEBUG] Hyperparameters: {'lr': 2.8765060980140754e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 32, 'dropout': 0.060696104622188135, 'batch': 8, 'warmup': 0.0444097957518081}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8305877447128296
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6554287672042847, 'eval_runtime': 66.7538, 'eval_samples_per_second': 1.873, 'eval_steps_per_second': 0.24, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6554287672042847

[I 2026-02-23 21:27:49,374] Trial 13 finished with value: 0.6554287672042847 and parameters: {'learning_rate': 2.8765060980140754e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.060696104622188135, 'batch_size': 8, 'warmup_ratio': 0.0444097957518081}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 13 finished successfully

========== STARTING TRIAL 14 ==========
[DEBUG] Hyperparameters: {'lr': 2.7597527534540282e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 32, 'dropout': 0.05610303615816015, 'batch': 16, 'warmup': 0.05217001251486819}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 0
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.024360179901123
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.8816291093826294, 'eval_runtime': 67.0318, 'eval_samples_per_second': 1.865, 'eval_steps_per_second': 0.119, 'epoch': 2.0}
[DEBUG] Validation loss: 0.8816291093826294

[I 2026-02-23 21:55:58,232] Trial 14 finished with value: 0.8816291093826294 and parameters: {'learning_rate': 2.7597527534540282e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.05610303615816015, 'batch_size': 16, 'warmup_ratio': 0.05217001251486819}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 14 finished successfully

========== STARTING TRIAL 15 ==========
[DEBUG] Hyperparameters: {'lr': 1.6142022568257205e-05, 'scheduler': 'linear', 'r': 32, 'alpha': 16, 'dropout': 0.10456562412251844, 'batch': 4, 'warmup': 0.04498805092878187}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.9186204969882965
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.7133086323738098, 'eval_runtime': 74.6831, 'eval_samples_per_second': 1.674, 'eval_steps_per_second': 0.428, 'epoch': 2.0}
[DEBUG] Validation loss: 0.7133086323738098

[I 2026-02-23 22:27:56,556] Trial 15 finished with value: 0.7133086323738098 and parameters: {'learning_rate': 1.6142022568257205e-05, 'lr_scheduler': 'linear', 'lora_r': 32, 'lora_alpha': 16, 'lora_dropout': 0.10456562412251844, 'batch_size': 4, 'warmup_ratio': 0.04498805092878187}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 15 finished successfully

========== STARTING TRIAL 16 ==========
[DEBUG] Hyperparameters: {'lr': 2.7384202233132056e-05, 'scheduler': 'cosine', 'r': 8, 'alpha': 32, 'dropout': 0.0536285254601173, 'batch': 8, 'warmup': 0.0845668927880707}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.8323541283607483
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6630268096923828, 'eval_runtime': 72.3076, 'eval_samples_per_second': 1.729, 'eval_steps_per_second': 0.221, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6630268096923828

[I 2026-02-23 22:56:59,908] Trial 16 finished with value: 0.6630268096923828 and parameters: {'learning_rate': 2.7384202233132056e-05, 'lr_scheduler': 'cosine', 'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.0536285254601173, 'batch_size': 8, 'warmup_ratio': 0.0845668927880707}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 16 finished successfully

========== STARTING TRIAL 17 ==========
[DEBUG] Hyperparameters: {'lr': 2.8379894603274056e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 16, 'dropout': 0.07729309875816626, 'batch': 8, 'warmup': 0.033394024848459346}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.9667804837226868
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.8082680106163025, 'eval_runtime': 66.2648, 'eval_samples_per_second': 1.886, 'eval_steps_per_second': 0.241, 'epoch': 2.0}
[DEBUG] Validation loss: 0.8082680106163025

[I 2026-02-23 23:26:32,744] Trial 17 finished with value: 0.8082680106163025 and parameters: {'learning_rate': 2.8379894603274056e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 16, 'lora_dropout': 0.07729309875816626, 'batch_size': 8, 'warmup_ratio': 0.033394024848459346}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 17 finished successfully

========== STARTING TRIAL 18 ==========
[DEBUG] Hyperparameters: {'lr': 1.5942837311104357e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 32, 'dropout': 0.07772907599846299, 'batch': 4, 'warmup': 0.03262685478194983}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7832210212945938
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6398540735244751, 'eval_runtime': 82.7861, 'eval_samples_per_second': 1.51, 'eval_steps_per_second': 0.387, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6398540735244751

[I 2026-02-23 23:58:12,413] Trial 18 finished with value: 0.6398540735244751 and parameters: {'learning_rate': 1.5942837311104357e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.07772907599846299, 'batch_size': 4, 'warmup_ratio': 0.03262685478194983}. Best is trial 11 with value: 0.6383668184280396.

[DEBUG] Trial 18 finished successfully

========== STARTING TRIAL 19 ==========
[DEBUG] Hyperparameters: {'lr': 1.785856585068423e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 32, 'dropout': 0.10478009278968822, 'batch': 4, 'warmup': 0.037588133949496734}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 2
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.7618516236543655
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6264609098434448, 'eval_runtime': 74.5668, 'eval_samples_per_second': 1.676, 'eval_steps_per_second': 0.429, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6264609098434448

[I 2026-02-24 00:30:03,637] Trial 19 finished with value: 0.6264609098434448 and parameters: {'learning_rate': 1.785856585068423e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.10478009278968822, 'batch_size': 4, 'warmup_ratio': 0.037588133949496734}. Best is trial 19 with value: 0.6264609098434448.

[DEBUG] Trial 19 finished successfully

========== STARTING TRIAL 20 ==========
[DEBUG] Hyperparameters: {'lr': 1.6928367391689294e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 32, 'dropout': 0.13072272838399024, 'batch': 16, 'warmup': 0.07264486684791205}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 15
[DEBUG] Warmup steps: 1
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 1.1411763429641724
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 1.0515434741973877, 'eval_runtime': 70.2145, 'eval_samples_per_second': 1.78, 'eval_steps_per_second': 0.114, 'epoch': 2.0}
[DEBUG] Validation loss: 1.0515434741973877

[I 2026-02-24 00:58:20,065] Trial 20 finished with value: 1.0515434741973877 and parameters: {'learning_rate': 1.6928367391689294e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.13072272838399024, 'batch_size': 16, 'warmup_ratio': 0.07264486684791205}. Best is trial 19 with value: 0.6264609098434448.

[DEBUG] Trial 20 finished successfully

========== STARTING TRIAL 21 ==========
[DEBUG] Hyperparameters: {'lr': 1.979602451146707e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 32, 'dropout': 0.09516165515176236, 'batch': 4, 'warmup': 0.048199183355596815}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Training finished
[DEBUG] Training loss: 0.7437325716018677
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.6157774329185486, 'eval_runtime': 74.7621, 'eval_samples_per_second': 1.672, 'eval_steps_per_second': 0.428, 'epoch': 2.0}
[DEBUG] Validation loss: 0.6157774329185486

[I 2026-02-24 01:30:10,248] Trial 21 finished with value: 0.6157774329185486 and parameters: {'learning_rate': 1.979602451146707e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 32, 'lora_dropout': 0.09516165515176236, 'batch_size': 4, 'warmup_ratio': 0.048199183355596815}. Best is trial 21 with value: 0.6157774329185486.

[DEBUG] Trial 21 finished successfully

========== STARTING TRIAL 22 ==========
[DEBUG] Hyperparameters: {'lr': 2.3946994838887218e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 8, 'dropout': 0.09681182180419443, 'batch': 4, 'warmup': 0.06453813525435674}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 62
[DEBUG] Warmup steps: 4
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

[DEBUG] Training finished
[DEBUG] Training loss: 0.9203455299139023
[DEBUG] Starting evaluation...

[DEBUG] Eval metrics: {'eval_loss': 0.7217969298362732, 'eval_runtime': 83.1859, 'eval_samples_per_second': 1.503, 'eval_steps_per_second': 0.385, 'epoch': 2.0}
[DEBUG] Validation loss: 0.7217969298362732

[I 2026-02-24 02:02:09,421] Trial 22 finished with value: 0.7217969298362732 and parameters: {'learning_rate': 2.3946994838887218e-05, 'lr_scheduler': 'cosine_with_restarts', 'lora_r': 32, 'lora_alpha': 8, 'lora_dropout': 0.09681182180419443, 'batch_size': 4, 'warmup_ratio': 0.06453813525435674}. Best is trial 21 with value: 0.6157774329185486.

[DEBUG] Trial 22 finished successfully

========== STARTING TRIAL 23 ==========
[DEBUG] Hyperparameters: {'lr': 2.1210793835026043e-05, 'scheduler': 'cosine_with_restarts', 'r': 32, 'alpha': 32, 'dropout': 0.12731452951468494, 'batch': 8, 'warmup': 0.030759126770191155}
[DEBUG] Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[DEBUG] Model loaded
[DEBUG] Applying LoRA...
trainable params: 79,953,920 || all params: 6,818,369,536 || trainable%: 1.1726
[DEBUG] Total steps: 31
[DEBUG] Warmup steps: 0
[DEBUG] Building TrainingArguments...
[DEBUG] Initializing Trainer...
[DEBUG] Starting training...

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)